import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "../appLayout/Header";
import Footer from "../appLayout/Footer";
import PageTransition from "../shared/components/common/PageTransition";
import { Toaster } from "react-hot-toast";
import QueryProvider from "@/lib/tanstack/provider";

import { Provider } from "react-redux";
import { Store } from "@/stores/store";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* <Provider store={Store}> */}
        <QueryProvider>
          <Header />
          <PageTransition>{children}</PageTransition>
          <Footer />
          <Toaster
            position="top-right"
            toastOptions={{
              duration: 4000,
              style: {
                background: "#333",
                color: "#fff",
                fontSize: "12px",
              },
            }}
          />
        </QueryProvider>
        {/* </Provider> */}
      </body>
    </html>
  );
}
